name: Analyse

on:
  push:
    paths:
        - '**.php'
        - 'phpstan.neon.dist'
  pull_request:
    paths:
        - '**.php'
        - 'phpstan.neon.dist'

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4

    - name: Install composer dependencies
      uses: ramsey/composer-install@v3

    - name: Run analyse phpstan
      run: vendor/bin/phpstan analyse --error-format github
